library(plotrix)
require(plotrix)
mydata=read.table('data.txt')
plot(mydata, ylab='d(omega_500_up)/omeg_500_up', xlab='dP/P - dq/q', xlim=c(-0.2,0.02), ylim=c(-0.2,0.02), main='Model upward mass flux change vs. inferred', pch=3, cex.main=1.5, frame.plot=TRUE, col='blue')
reg<-lm(V2~V1, data=mydata)
abline(reg, lty='dashed')
abline(h = 0, v = 0, col = "gray60")
abline(a=0,b=1,col = "gray60")
xy<-plotrix::emptyspace(mydata)
plotrix::boxed.labels(xy,bty='n',labels=paste("R^2=", format(summary(reg)$r.squared, digits=4)),border=FALSE)
numbers <- c("1","2","3","4","5","6","7","8","9","10")
text(mydata, numbers, cex=0.7, pos=1)
